image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build

style-test:
  image: python:3.8.5
  stage: test
  # allow_failure: true

  before_script:
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
  script:
    - pycodestyle ./prj1a/urls.py
    - PYCODESTYLE_RET=$?
    - if [ $PYCODESTYLE_RET \> 0 ]; then exit $PYCODESTYLE_RET; fi;
    - exit $PYCODESTYLE_RET

unit-test:
  image: python:3.8.5
  stage: test
   #allow_failure: true

  before_script:
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate
  script:
    - python3 manage.py test
    - UNIT_TEST_RET=$?
    - if [ $UNIT_TEST_RET \> 0 ]; then exit $UNIT_TEST_RET; fi;
    - exit $UNIT_TEST_RET

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master