# Generated by Django 4.0.3 on 2022-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True,
                                                   serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('carplate', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
