# Generated by Django 4.0.4 on 2022-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
