# Generated by Django 4.0.3 on 2022-04-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lat', models.FloatField()),
                ('from_long', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_long', models.FloatField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger')),
            ],
        ),
    ]
