# Generated by Django 4.0.3 on 2022-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='est_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
