# Generated by Django 4.0.4 on 2022-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(default='0'),
        ),
    ]
